version: '3.8'

services:
  web-template:
    build:
      context: docker/nginx
      dockerfile: nginx.Dockerfile
    container_name: web-template
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/Tracer.local.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/symfony-cors.conf:/etc/nginx/symfony-cors.conf
