<?php

declare(strict_types=1);

namespace Migrations\V1\Habits;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250626134651Createhabitshistory extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание таблицы habits_history с проверкой на существование (PostgreSQL)';
    }

    public function up(Schema $schema): void
    {
        $sm = $this->connection->createSchemaManager();

        if (!$sm->tablesExist(['habits_history'])) {
            $this->addSql(<<<'SQL'
                CREATE TABLE habits_history (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    count INTEGER NOT NULL,
                    habits_id INTEGER NOT NULL,
                    count_end INTEGER NOT NULL,
                    is_done BOOLEAN NOT NULL,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP DEFAULT NULL,
                    is_deleted BOOLEAN NOT NULL
                )
            SQL);
        }
    }

    public function down(Schema $schema): void
    {
        $sm = $this->connection->createSchemaManager();

        if ($sm->tablesExist(['habits_history'])) {
            $this->addSql('DROP TABLE habits_history');
        }
    }
}
