parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Twig\ViteAssetExtension:
        tags: [ 'twig.extension' ]



    App\Infrastructure\EventListener\Exceptions\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 100 }

