parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Twig\ViteAssetExtension:
        tags: [ 'twig.extension' ]



    App\Infrastructure\EventListener\Exceptions\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 100 }

    App\Infrastructure\Service\FilterCriteriaApply\CriteriaApplicators\:
        resource: '../src/Infrastructure/Service/FilterCriteriaApply/CriteriaApplicators/*'
        tags: [ 'app.criterion_applier' ]

    App\Infrastructure\Service\FilterCriteriaApply\FilterApplicator\ApplyFilter:
        arguments:
            $criterionAppliers: !tagged_iterator app.criterion_applier
