<?php

declare(strict_types=1);

namespace Migrations\V1\Users;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250617181327_create_users_table extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание таблиц Users и messenger_messages, если они ещё не существуют';
    }

    public function up(Schema $schema): void
    {
        $sm = $this->connection->createSchemaManager();

        if (!$sm->tablesExist(['Users'])) {
            $this->addSql(<<<'SQL'
                CREATE TABLE Users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    email VARCHAR(255) NOT NULL,
                    password VARCHAR(255) NOT NULL,
                    premium INTEGER NOT NULL,
                    role VARCHAR(35) NOT NULL
                )
            SQL);
        }

        if (!$sm->tablesExist(['messenger_messages'])) {
            $this->addSql(<<<'SQL'
                CREATE TABLE messenger_messages (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    body TEXT NOT NULL,
                    headers TEXT NOT NULL,
                    queue_name VARCHAR(190) NOT NULL,
                    created_at TIMESTAMP NOT NULL,
                    available_at TIMESTAMP NOT NULL,
                    delivered_at TIMESTAMP
                )
            SQL);


            $this->addSql('CREATE INDEX IDX_QUEUE_NAME ON messenger_messages(queue_name)');
            $this->addSql('CREATE INDEX IDX_AVAILABLE_AT ON messenger_messages(available_at)');
            $this->addSql('CREATE INDEX IDX_DELIVERED_AT ON messenger_messages(delivered_at)');
        }
    }

    public function down(Schema $schema): void
    {
        $sm = $this->connection->createSchemaManager();

        if ($sm->tablesExist(['messenger_messages'])) {
            $this->addSql('DROP TABLE messenger_messages');
        }

        if ($sm->tablesExist(['Users'])) {
            $this->addSql('DROP TABLE Users');
        }
    }
}
