<?php

declare(strict_types=1);

namespace Migrations\V1\Pomodoro;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250622052239_created_table_pomodoro_history extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание таблицы pomodoro_history (PostgreSQL совместимость)';
    }

    public function up(Schema $schema): void
    {
        $schemaManager = $this->connection->createSchemaManager();

        if (!$schemaManager->tablesExist(['pomodoro_history'])) {
            $this->addSql(<<<'SQL'
                CREATE TABLE pomodoro_history (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id INTEGER NOT NULL,
                    time_focus INTEGER NOT NULL,
                    period_label VARCHAR(10) NOT NULL,
                    focus_start TIMESTAMP NOT NULL,
                    focus_end TIMESTAMP NOT NULL,
                    create_date TIMESTAMP NOT NULL,
                    update_date TIMESTAMP DEFAULT NULL,
                    is_delete BOOLEAN NOT NULL DEFAULT FALSE
                )
            SQL);
        }
    }

    public function down(Schema $schema): void
    {
        $schemaManager = $this->connection->createSchemaManager();

        if ($schemaManager->tablesExist(['pomodoro_history'])) {
            $this->addSql('DROP TABLE pomodoro_history');
        }
    }
}
