name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Clear & warmup dev cache
        run: |
          php bin/console cache:clear --env=dev
          php bin/console cache:warmup --env=dev
      - name: Run PHPStan
        run: APP_ENV=dev vendor/bin/phpstan analyse src

  csfixer:
    runs-on: ubuntu-latest
    needs: phpstan
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
